### ISSUE TITLE
Change the eye icon for pencil icon

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo#79] opened 2022-11-18 01:14 UTC
#### Issue description
The users are confused when needs edit check

![image](https://user-images.githubusercontent.com/35310226/202593781-a188ebee-fba9-4f2f-93b4-9ae53ccedf44.png)

#### Steps to reproduce the issue

1.  Go to the app
2. Go to checks page

#### What's the expected result?

- Change the icon of the edit button using the icon pack [https://akveo.github.io/eva-icons/#/](https://akveo.github.io/eva-icons/#/)

**Comment by loki1205** [comment] 2022-11-18 10:20
Hi, my name is Loknath Kumar Mishra, I would like to contribute. Can you please assign this to me?

**Comment by itsalb3rt** [comment] 2022-11-18 20:12
Yes, sure! @loki1205

**Comment by loki1205** [comment] 2022-11-19 03:13
Hi, I cannot reproduce the same issue again. Can you guide me how to run the app on my local computer so that I can be sure that I am not commiting any mistakes.

**Comment by itsalb3rt** [comment] 2022-11-19 13:53
No problem, I guide you to run the app locally.

**Frontend**

- First clone the frontend repository
```bash
git clone https://github.com/ta-vivo/ta-vivo
```
- run `yarn install` or `npm install`
- Create the `.env` file from the `.env.example` and keep the default values.
- Run the app with `quasar dev` command;

More information: [https://documentation.tavivo.do/front-end/#setup](https://documentation.tavivo.do/front-end/#setup)

**Backend**

- Clone the respository 
```bash
git clone https://github.com/ta-vivo/ta-vivo-api
```
- Run `yarn install` or `npm install`
- Create the `.env` file from the `.env.example` and keep the default values except the databse connection, at this point you need a postgres database running in your environment. Go to your `.env` file and change all the values
```bash
# Database
DATABASE_HOST=localhost
DATABASE_PORT=5444
DATABASE_NAME=postgres
DATABASE_USER=postgres
DATABASE_PASSWORD=postgres
```
- Now you can run the app with `yarn dev` or `npm run dev`

More information: [https://documentation.tavivo.do/back-end/#setup](https://documentation.tavivo.do/back-end/#setup)

---

When you running the Frontend and the Backend the default user is `admin@tavivo.com` and the password is `secret`

**Comment by itsalb3rt** [comment] 2022-11-22 00:46
@loki1205 are you working on that ?

**Comment by itsalb3rt** [comment] 2022-11-26 23:42
Reassigned by inactivity

**Closed** 2022-11-26 23:49 UTC
Labels: bug, help wanted, good first issue
